name: Fintrack
description: "Projeto de organização financeira - C214-L1"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0" # DART VERSION

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Fornece ícones no estilo iOS para uso com a classe CupertinoIcons.
  pie_chart: ^5.4.0 # Adiciona suporte para criação de gráficos de pizza no aplicativo.
  http: ^1.2.2 # Pacote HTTP para fazer requisições de rede.
  shared_preferences: ^2.3.2 # Permite armazenar dados simples localmente em pares chave-valor.

dev_dependencies:
  flutter_test:
    sdk: flutter # Fornece suporte a testes para aplicativos Flutter.
  flutter_lints: ^3.0.0 # Incentiva boas práticas de codificação com um conjunto de regras de lint recomendadas.

flutter:
  uses-material-design: true # USO DE ICONES
